# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmFkMDYzMmQ4MGQzZjYxOTc1YWYwOTllN2E3ZDc4MTIwZjJkMDAyM2RmZTBlZjliYmEwYmFjYjU4NGU0MmI2ODcyZDI1NjVhZDk3YmU4ZDI5MmU0N2E2MjkyNzc1YWZhNzA2ZTVlMDliYzQ0YzM0ZTYyZjMzOWNhODVhYjk4MWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
