apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/authenticationapisservice
      context: ../authenticationApisService
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/batteryapisservice
      context: ../batteryApisService
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/bssapisservice
      context: ../bssApisService
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/devicestateapiservice
      context: ../deviceStateApiService
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/gateway
      context: ../gateway
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/supportapisservice
      context: ../supportApisService
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/swapapiservice
      context: ../swapApiService
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/userapisservice
      context: ../userApisService
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/vehicleapiservice
      context: ../vehicleApiService
      jib: {}
    - image: 099919086460.dkr.ecr.ap-southeast-1.amazonaws.com/vehiclestateapis
      context: ../vehicleStateApis
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
