export enum SosState {
  SEND_REQUEST = 'SEND_REQUEST',

  REQUEST_RECEIVED = 'REQUEST_RECEIVED',

  ASSIGNMENT = 'ASSIGNMENT',

  HANDLE_START = 'HANDLE_START',

  HANDLE_DONE = 'HANDLE_DONE',

  USERS_RATED = 'USERS_RATED',
}
