apiVersion: v1
kind: Service
metadata:
  name: vehiclestateapis
  namespace: iot
  labels:
    app: vehiclestateapis
spec:
  selector:
    app: vehiclestateapis
  ports:
    - name: http
      port: 8081
