apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bssapisservice-app
  namespace: iot
  labels:
    team: iot
spec:
  selector:
    matchLabels:
      app: bssapisservice
  endpoints:
    - port: web
      path: /prometheusMetrics
